Failing test
OskarStark/SonataDoctrineORMAdminBundle pull request #1
Opened 2017-06-27 18:01 UTC by greg0ire

@OskarStark you should rebase your branch before merging this

2017-06-27 18:03 UTC, greg0ire commented on Tests/Guesser/FilterTypeGuesserTest.php
> +        $this->modelManager = $this->prophesize('Sonata\DoctrineORMAdminBundle\Model\ModelManager');
Here, I can't mock the interface, it does not have the method we are using (which is a separate issue)

2017-06-28 04:33 UTC, OskarStark requested changes

2017-06-28 04:33 UTC, OskarStark commented on Tests/Guesser/FilterTypeGuesserTest.php
> +        $this->setExpectedException(
should be an annotation, since `setExpectedException` is deprecated

2017-06-28 04:33 UTC, OskarStark commented
I rebased the branch @greg0ire

2017-06-28 08:59 UTC, OskarStark approved these changes

2017-06-28 08:59 UTC, merged